import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [imgSrc, setImgSrc] = useState(null);

  const handleChange = (e) => {
    if (e.target.files && e.target.files[0] && e.target.files.length < 10) {
      const fileList = e.target.files;
      const fileArray = [];
      Object.keys(fileList).map((element) => {
        fileArray.push(URL.createObjectURL(fileList[element]));
      });
      setImgSrc(fileArray);
    }
    return;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const form = e.currentTarget;
    const cloudName = 'dtgbzmpca';
    const upPreset = 'wgyszbgz';
    const fileInput = Array.from(form.elements).find(
      ({ name }) => name === 'img'
    );
    const fileChildren = [];

    const formData = new FormData();

    formData.append('upload_preset', upPreset);

    Object.keys(fileInput.files).map((element) => {
      fileChildren.push(fileInput.files[element]);
    });

    const request = () =>
      fileChildren.map((file) => {
        formData.append('file', file);
        fetch(`https://api.cloudinary.com/v1_1/${cloudName}/image/upload`, {
          method: 'POST',
          body: formData,
        });
      });

    Promise.all(request())
      .then((res) => {
        alert('File(s) Uploaded successsfully');
        setImgSrc(null);
      })
      .catch((e) => alert('Error uploading file'));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Bulk upload</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>Cloudinary Bulk Upload</p>

        <form method='post' onSubmit={handleSubmit}>
          <label htmlFor='img' className={styles.label}>
            Select image:
          </label>
          <input
            type='file'
            name='img'
            accept='image/*'
            required
            multiple
            className={styles.fileUpload}
            onChange={handleChange}
          />
          <div className={styles.grid}></div>
          {imgSrc &&
            imgSrc.map((image, i) => (
              <img key={i} src={image} className={styles.img} />
            ))}
          <button className={styles.button}>Submit</button>
        </form>
      </main>
    </div>
  );
}
